{
 "title": "Flask DevOps App — Dashboard",
 "tags": [
  "devops",
  "flask",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "🟢 Pods Running",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace='devops-tp', phase='Running'})",
     "legendFormat": "Pods actifs"
    }
   ]
  },
  {
   "title": "🔄 Pod Restarts (1h)",
   "type": "stat",
   "gridPos": { "x": 4, "y": 0, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace='devops-tp'}[1h]))",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "📡 Trafic entrant (req/s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(app_request_count_total{namespace='devops-tp'}[5m])",
     "legendFormat": "{{endpoint}} [{{status}}]"
    }
   ]
  },
  {
   "title": "⚡ CPU Usage par Pod",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace='devops-tp', container='flask-devops-app'}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "🧠 RAM Usage par Pod",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace='devops-tp', container='flask-devops-app'}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "⏱️ Latence (p99)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(app_request_latency_seconds_bucket{namespace='devops-tp'}[5m]))",
     "legendFormat": "p99 — {{endpoint}}"
    }
   ]
  }
 ]
}